INSERT INTO `manufacturers` (`id`, `name`, `description`, `logo`) VALUES
(1, 'Chicco', 'Chicco description', '/storage/manufacturer/chicco.png'),
(2, 'Barbie', 'Barbie description', '/storage/manufacturer/barbie.png'),
(3, 'Benneton', 'Benneton description', '/storage/manufacturer/benneton.png'),
(4, 'Gap', 'Gap description', '/storage/manufacturer/gap.png'),
(5, 'Heinz', 'Heinz description', '/storage/manufacturer/heinz.png'),
(6, 'Hipp', 'Hipp description', '/storage/manufacturer/hipp.png'),
(7, 'Huggies', 'Huggies description', '/storage/manufacturer/huggies.png'),
(8, 'Pampers', 'Pampers description', '/storage/manufacturer/pampers.png'),
(9, 'Humana', 'Humana description', '/storage/manufacturer/humana.png'),
(10, 'Lego', 'Lego description', '/storage/manufacturer/lego.png'),
(11, 'Zara', 'Zara description', '/storage/manufacturer/zara.png'),
(12, 'Libero', 'Այս ընկերությունն արտադրում է տարբեր հիգիենայի պարագաներ, անձեռոցիկներ, թղթեր և այլն, իսկ Libero բրենդով թողարկվում են տակդիրներ, վարտիք-տակդիրներ, թաց անձեռոցիկներ և այլ մանկական հիգիենայի պարագաներ։', '/storage/manufacturer/ef54b13873679b1b9f65e527a7282a9f.png'),
(13, 'Similac', 'Similac (Abbott Laboratories)', '/storage/manufacturer/84513bd98e812b1217ab365a8bfe07ce.jpg'),
(14, 'Semper', 'Semper AB', '/storage/manufacturer/1a0ff8b7962908d65fa943ba5256653d.jpg'),
(15, 'Nordic', 'Nordic Raisio', '/storage/manufacturer/a0063d64ddf8c275eda0104b4e33c297.jpg'),
(16, 'Carter\'s', 'Carter\'s', '/storage/manufacturer/0ee2d415bf2084bad80094f916d91d66.jpg');
